### ISSUE TITLE
Chart for the demo-app failed to add the environment variable for the socket or the volume

### ISSUE THREAD

**Issue by jicowan** [elinesterov/spiffe-demo-app#20]
After adding the helm repository for the demo-app, installing the chart applies the following manifests: 
```
helm template -n spiffe-demo spiffe-demo  spiffe-demo/spiffe-demo-app --set app.spiffeSocketName=spire-agent.sock        
---
# Source: spiffe-demo-app/templates/sa.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spiffe-demo-app
  namespace: spiffe-demo
---
# Source: spiffe-demo-app/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: spiffe-demo-service
  namespace: spiffe-demo
spec:
  selector:
    app: spiffe-demo-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
  
  type: LoadBalancer
---
# Source: spiffe-demo-app/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spiffe-demo-app
  namespace: spiffe-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spiffe-demo-app
  template:
    metadata:
      labels:
        app: spiffe-demo-app
        k8s.spirl.com/spiffe-csi: enabled
    spec:
      serviceAccountName: spiffe-demo-app
      containers:
      - name: spiffe-demo-app
        image: ghcr.io/elinesterov/spiffe-demo-app:v0.2.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
```
